from sqlalchemy.orm import Session
from app.database.database import engine, Base, SessionLocal
from app.models.hospital import Hospital
from app.models.ambulance import Ambulance
from app.models.incident import Incident
from app.models.agent import Agent
from app.models.audit_log import AuditLog


def seed_db(db: Session):
    # Always ensure full rich seed data exists
    if db.query(Hospital).count() < 18:
        db.query(Hospital).delete()
        hospitals = [
            Hospital(
                name="Apollo Main Super Specialty",
                location="Greams Road",
                lat=13.0604,
                lng=80.2496,
                available_beds=18,
                total_beds=120,
                icu_beds=15,
                status="Available",
                contact="+91 44 2829 0200",
                specialties="Cardiology, Organ Transplant, Emergency ICU",
            ),
            Hospital(
                name="MIOT International Trauma Care",
                location="Manapakkam",
                lat=13.0232,
                lng=80.1764,
                available_beds=14,
                total_beds=100,
                icu_beds=12,
                status="Available",
                contact="+91 44 2249 2288",
                specialties="Polytrauma, Orthopedics, Critical Care",
            ),
            Hospital(
                name="Fortis Malar Hospital",
                location="Adyar",
                lat=13.0067,
                lng=80.2572,
                available_beds=0,
                total_beds=75,
                icu_beds=8,
                status="Full",
                contact="+91 44 4289 2222",
                specialties="Pediatrics, Cardiac Surgery, ICU",
            ),
            Hospital(
                name="Kauvery Super Specialty",
                location="Alwarpet",
                lat=13.0336,
                lng=80.2520,
                available_beds=9,
                total_beds=60,
                icu_beds=7,
                status="Available",
                contact="+91 44 4000 6000",
                specialties="General Emergency, Stroke Center",
            ),
            Hospital(
                name="Gleneagles Global Health City",
                location="Perumbakkam",
                lat=12.9038,
                lng=80.1983,
                available_beds=32,
                total_beds=150,
                icu_beds=25,
                status="Available",
                contact="+91 44 4624 2424",
                specialties="Multi-Organ Transplant, Level 1 Trauma",
            ),
            Hospital(
                name="SIMS Hospital",
                location="Vadapalani",
                lat=13.0500,
                lng=80.2121,
                available_beds=21,
                total_beds=90,
                icu_beds=16,
                status="Available",
                contact="+91 44 2000 2000",
                specialties="Neuroscience, Advanced Cardiac ICU",
            ),
            Hospital(
                name="Chettinad Super Specialty",
                location="Kelambakkam - OMR",
                lat=12.7915,
                lng=80.2189,
                available_beds=40,
                total_beds=200,
                icu_beds=30,
                status="Available",
                contact="+91 44 4741 1000",
                specialties="Disaster Relief, Burns & Plastic Surgery",
            ),
            Hospital(
                name="Government General Hospital (RGGGH)",
                location="Park Town",
                lat=13.0815,
                lng=80.2764,
                available_beds=5,
                total_beds=300,
                icu_beds=45,
                status="Emergency Only",
                contact="+91 44 2530 5000",
                specialties="Public Emergency, Toxicology, Mass Casualty",
            ),
            Hospital(
                name="MGM Healthcare",
                location="Aminjikarai",
                lat=13.0722,
                lng=80.2195,
                available_beds=26,
                total_beds=140,
                icu_beds=22,
                status="Available",
                contact="+91 44 4524 2424",
                specialties="ECMO Center, Heart Transplant, Stroke ICU",
            ),
            Hospital(
                name="Sri Ramachandra Medical Centre",
                location="Porur",
                lat=13.0360,
                lng=80.1448,
                available_beds=38,
                total_beds=250,
                icu_beds=35,
                status="Available",
                contact="+91 44 4592 8500",
                specialties="Level 1 Trauma, Burn ICU, Telemedicine",
            ),
            Hospital(
                name="Dr. Rela Institute & Medical Centre",
                location="Chromepet",
                lat=12.9516,
                lng=80.1462,
                available_beds=19,
                total_beds=110,
                icu_beds=18,
                status="Available",
                contact="+91 44 6666 7777",
                specialties="Abdominal Trauma, Paediatric Intensive Care",
            ),
            Hospital(
                name="Voluntary Health Services (VHS)",
                location="Taramani",
                lat=12.9868,
                lng=80.2464,
                available_beds=15,
                total_beds=80,
                icu_beds=10,
                status="Available",
                contact="+91 44 2254 1972",
                specialties="Community Trauma, Snakebite & Poisoning Unit",
            ),
            Hospital(
                name="Billroth Super Specialty Hospital",
                location="Shenoy Nagar",
                lat=13.0782,
                lng=80.2241,
                available_beds=22,
                total_beds=115,
                icu_beds=14,
                status="Available",
                contact="+91 44 2664 1777",
                specialties="Gastroenterology ICU, Vascular Surgery, Trauma",
            ),
            Hospital(
                name="Dr. Mehta Multispeciality Hospital",
                location="Chetpet",
                lat=13.0718,
                lng=80.2415,
                available_beds=17,
                total_beds=95,
                icu_beds=12,
                status="Available",
                contact="+91 44 4005 4005",
                specialties="Pediatric Emergency, Neonatology, Critical Care",
            ),
            Hospital(
                name="Sundaram Medical Foundation (SMF)",
                location="Anna Nagar West",
                lat=13.0890,
                lng=80.2085,
                available_beds=11,
                total_beds=85,
                icu_beds=10,
                status="Available",
                contact="+91 44 2626 8844",
                specialties="Community Emergency, Stroke & Cardiac Triage",
            ),
            Hospital(
                name="Apollo First Med Hospital",
                location="Kilpauk",
                lat=13.0789,
                lng=80.2440,
                available_beds=14,
                total_beds=70,
                icu_beds=9,
                status="Available",
                contact="+91 44 2829 3333",
                specialties="Cardiology, Emergency Diagnostics, ICU",
            ),
            Hospital(
                name="SRM Medical College Hospital",
                location="Kattankulathur",
                lat=12.8231,
                lng=80.0442,
                available_beds=45,
                total_beds=350,
                icu_beds=40,
                status="Available",
                contact="+91 44 2745 2270",
                specialties="Mass Casualty Response, Tertiary Trauma, ICU",
            ),
            Hospital(
                name="Vijaya Health Centre",
                location="Vadapalani Hub",
                lat=13.0512,
                lng=80.2105,
                available_beds=20,
                total_beds=130,
                icu_beds=16,
                status="Available",
                contact="+91 44 2480 1600",
                specialties="Cardiothoracic Surgery, Neuro ICU, Emergency",
            ),
        ]
        db.add_all(hospitals)
        db.commit()

    if db.query(Ambulance).count() < 18:
        db.query(Ambulance).delete()
        ambulances = [
            Ambulance(
                vehicle_number="TN-01-AM-1001",
                driver_name="Ramesh Kumar",
                contact="+91 98765 43210",
                location="Anna Nagar West Hub",
                lat=13.0850,
                lng=80.2101,
                status="Available",
                type="Advanced Life Support (ALS)",
            ),
            Ambulance(
                vehicle_number="TN-07-AM-1002",
                driver_name="Suresh Babu",
                contact="+91 98765 43211",
                location="Velachery Junction",
                lat=12.9750,
                lng=80.2206,
                status="On Duty",
                type="Basic Life Support (BLS)",
            ),
            Ambulance(
                vehicle_number="TN-09-AM-1003",
                driver_name="Venkatesh S",
                contact="+91 98765 43212",
                location="Tambaram Railway Hub",
                lat=12.9249,
                lng=80.1000,
                status="Available",
                type="Neonatal Care ICU Unit",
            ),
            Ambulance(
                vehicle_number="TN-02-AM-1004",
                driver_name="Karthik M",
                contact="+91 98765 43213",
                location="OMR Sholinganallur Tech Park",
                lat=12.9010,
                lng=80.2279,
                status="Available",
                type="Advanced Life Support (ALS)",
            ),
            Ambulance(
                vehicle_number="TN-10-AM-1005",
                driver_name="Dinesh Verma",
                contact="+91 98765 43214",
                location="T. Nagar Bus Terminus",
                lat=13.0418,
                lng=80.2341,
                status="Maintenance",
                type="Basic Life Support (BLS)",
            ),
            Ambulance(
                vehicle_number="AIR-HELI-01",
                driver_name="Capt. Vikram Roy",
                contact="+91 99999 88888",
                location="Chennai International Helipad",
                lat=12.9941,
                lng=80.1709,
                status="Available",
                type="Air Ambulance (Helicopter)",
            ),
            Ambulance(
                vehicle_number="TN-14-AM-1007",
                driver_name="Anand Prakash",
                contact="+91 98765 43217",
                location="Guindy Industrial Estate",
                lat=13.0067,
                lng=80.2020,
                status="Available",
                type="Cardiac Care Unit (CCU)",
            ),
            Ambulance(
                vehicle_number="TN-05-AM-1008",
                driver_name="Murugan P",
                contact="+91 98765 43218",
                location="Porur Junction",
                lat=13.0382,
                lng=80.1565,
                status="Available",
                type="Advanced Life Support (ALS)",
            ),
            Ambulance(
                vehicle_number="TN-11-AM-1009",
                driver_name="Dr. Shalini & Team",
                contact="+91 98765 43219",
                location="Nungambakkam High Rd",
                lat=13.0610,
                lng=80.2400,
                status="Available",
                type="Mobile Stroke CT Unit",
            ),
            Ambulance(
                vehicle_number="TN-04-AM-1010",
                driver_name="Ranganathan G",
                contact="+91 98765 43220",
                location="Koyambedu CMBT Terminal",
                lat=13.0694,
                lng=80.1948,
                status="Available",
                type="Heavy Extrication & Rescue Unit",
            ),
            Ambulance(
                vehicle_number="MOTO-MEDIC-01",
                driver_name="Subash Chander",
                contact="+91 98765 43221",
                location="Mylapore Kapaleeshwarar Zone",
                lat=13.0339,
                lng=80.2696,
                status="Available",
                type="Rapid First-Responder Motorbike",
            ),
            Ambulance(
                vehicle_number="AIR-HELI-02",
                driver_name="Wing Cdr. R. Sharma",
                contact="+91 99999 77777",
                location="Tambaram Air Force Base",
                lat=12.9070,
                lng=80.1170,
                status="Available",
                type="Air Ambulance (Helicopter)",
            ),
            Ambulance(
                vehicle_number="TN-06-AM-1014",
                driver_name="Prakash Raj",
                contact="+91 98765 43222",
                location="Chetpet Eco Park",
                lat=13.0720,
                lng=80.2420,
                status="Available",
                type="Basic Life Support (BLS)",
            ),
            Ambulance(
                vehicle_number="TN-13-AM-1015",
                driver_name="Senthil Nathan",
                contact="+91 98765 43223",
                location="Shenoy Nagar Metro Station",
                lat=13.0785,
                lng=80.2245,
                status="Available",
                type="Advanced Life Support (ALS)",
            ),
            Ambulance(
                vehicle_number="AIR-HELI-03",
                driver_name="Capt. Ananya Sen",
                contact="+91 99999 66666",
                location="Meenambakkam Air Evac Base",
                lat=12.9900,
                lng=80.1650,
                status="Available",
                type="Air Ambulance (Helicopter)",
            ),
            Ambulance(
                vehicle_number="MOTO-MEDIC-02",
                driver_name="Kishore Kumar",
                contact="+91 98765 43224",
                location="T. Nagar Pondy Bazaar Zone",
                lat=13.0400,
                lng=80.2330,
                status="Available",
                type="Rapid First-Responder Motorbike",
            ),
            Ambulance(
                vehicle_number="TN-18-AM-1016",
                driver_name="Gokulnath R",
                contact="+91 98765 43225",
                location="SRM University Campus",
                lat=12.8235,
                lng=80.0450,
                status="Available",
                type="Cardiac Care Unit (CCU)",
            ),
            Ambulance(
                vehicle_number="TN-22-AM-1017",
                driver_name="Manikandan K",
                contact="+91 98765 43226",
                location="Kilpauk Medical Zone",
                lat=13.0790,
                lng=80.2445,
                status="Available",
                type="Advanced Life Support (ALS)",
            ),
        ]
        db.add_all(ambulances)
        db.commit()

    if db.query(Incident).count() < 5:
        db.query(Incident).delete()
        incidents = [
            Incident(
                title="Multi-Vehicle Collision on GST Road",
                type="Road Accident",
                location="Anna Nagar Flyover",
                lat=13.0850,
                lng=80.2101,
                priority="Critical",
                status="Dispatching",
                ai_summary="High-speed 3-vehicle pileup. AI Triage classified scenario as Critical (Score 95).",
            ),
            Incident(
                title="Acute Myocardial Infarction",
                type="Heart Attack",
                location="Velachery Main Rd",
                lat=12.9750,
                lng=80.2206,
                priority="Critical",
                status="Ambulance Assigned",
                assigned_ambulance="TN-07-AM-1002",
                assigned_hospital="Apollo Main Super Specialty",
                recommended_route="Express Corridor via Inner Ring Rd ➔ Greams Rd (ETA: 7 mins)",
                ai_summary="Patient experiencing acute cardiac distress. ALS ambulance assigned with cardiac telemetry.",
            ),
            Incident(
                title="Commercial Warehouse Blaze",
                type="Fire Accident",
                location="Tambaram Industrial Area",
                lat=12.9249,
                lng=80.1000,
                priority="High",
                status="En Route",
                assigned_ambulance="TN-09-AM-1003",
                assigned_hospital="MIOT International Trauma Care",
                recommended_route="Tambaram Bypass ➔ Mount Poonamallee Rd (ETA: 11 mins)",
                ai_summary="Smoke inhalation & burn triage. Emergency response team dispatched.",
            ),
            Incident(
                title="Industrial Machine Injury",
                type="Trauma",
                location="OMR Sholinganallur Tech Park",
                lat=12.9010,
                lng=80.2279,
                priority="High",
                status="Ambulance Assigned",
                assigned_ambulance="TN-02-AM-1004",
                assigned_hospital="Gleneagles Global Health City",
                recommended_route="OMR Expressway Direct to Perumbakkam (ETA: 5 mins)",
                ai_summary="Limb trauma reported. Direct transfer to Level 1 Trauma Center.",
            ),
            Incident(
                title="Premature Infant Respiratory Distress",
                type="Neonatal Emergency",
                location="Guindy",
                lat=13.0067,
                lng=80.2020,
                priority="Critical",
                status="Dispatching",
                ai_summary="Neonatal ICU transport required. Incubator unit standby initiated.",
            ),
        ]
        db.add_all(incidents)
        db.commit()

    if db.query(Agent).count() < 6:
        db.query(Agent).delete()
        agents = [
            Agent(
                name="AI Telemetry & Intake Specialist",
                role="Emergency Call Intake & NLP Triage",
                status="Active",
                assigned_tasks=42,
            ),
            Agent(
                name="AI Green Corridor Optimizer",
                role="Traffic Signal Preemption & Route Generation",
                status="Processing",
                assigned_tasks=28,
            ),
            Agent(
                name="AI Fleet Allocation Swarm",
                role="Proximity & Equipment Matching",
                status="Active",
                assigned_tasks=56,
            ),
            Agent(
                name="AI Hospital Bed Lock Coordinator",
                role="Real-Time ICU & Bed Reservations",
                status="Active",
                assigned_tasks=39,
            ),
            Agent(
                name="AI Patient Tele-Monitoring Agent",
                role="In-Transit Vital Signs Tracking",
                status="Monitoring",
                assigned_tasks=19,
            ),
            Agent(
                name="AI Audit & Compliance Sentinel",
                role="System Telemetry & Audit Logs",
                status="Active",
                assigned_tasks=67,
            ),
        ]
        db.add_all(agents)
        db.commit()

    if db.query(AuditLog).count() < 6:
        db.query(AuditLog).delete()
        logs = [
            AuditLog(
                event="Emergency Call #9102 received from Velachery Junction", category="System"
            ),
            AuditLog(
                event="AI Intake Specialist categorized incident as Critical Cardiac Emergency (Score: 95/100)",
                category="AI Copilot",
            ),
            AuditLog(
                event="AI Fleet Allocation Swarm dispatched ALS Ambulance TN-07-AM-1002",
                category="Ambulance",
            ),
            AuditLog(
                event="AI Green Corridor Optimizer activated Signal Priority on Inner Ring Road",
                category="Traffic AI",
            ),
            AuditLog(
                event="Apollo Main Super Specialty reserved ICU Bed #04 for inbound patient",
                category="Hospital",
            ),
            AuditLog(
                event="Air Ambulance AIR-HELI-01 status set to Standby at Chennai Airport Helipad",
                category="Air Fleet",
            ),
        ]
        db.add_all(logs)
        db.commit()


if __name__ == "__main__":
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        seed_db(db)
        print("Database Seeded Successfully!")
    finally:
        db.close()


